<a href="https://colab.research.google.com/github/sanjanasridharan/Final/blob/master/day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world!")

hello world!


In [ ]:
x=23.4
print(x)
print(type(x))

23.4
<class 'float'>


In [ ]:
x=input("enter name:")
y=input("enter age:")
print(" {0} your age is {1}".format(x,y))

enter name:sanjana
enter age4
 sanjana's age is 4


In [ ]:
a=True
print(a+False)

1


In [ ]:
a='3'
print(a*3)

333


In [ ]:
a="sddd"
print(type(a))

<class 'str'>


In [ ]:
print(41/3)
print(41//3)

13.666666666666666
13


In [ ]:
print(5 is 5)

True


In [ ]:
x=24
if x>0:
 print("more")
else:
  print("less")

more


In [ ]:
n=int(input("enter n:"))
if n%2==0:
  print("even")
else:
   print("odd")

enter n:7
odd


In [ ]:
x=int(input("enter x:"))
y=int(input("enter y:"))
if x==y:
  print(x," is equal to",y)
elif x>y:
  print(x," is greater than",y)
else:
  print(x,'is less than',y)

enter x:2
enter y:2
2  is equal to 2


In [ ]:
x=1
y=0
print(x>=2 and (x/y >2)) 
print(x<=2 and (x/y >2)) #short circute evaluation

False


ZeroDivisionError: ignored

In [ ]:
a='car'
b='bus'
print(id(a)) #objects memory address
(a,b)=(b,a) #swap
print(a)
print(b)

139996155077048
bus
car


In [ ]:
#Q) Write a program to pay 1.5 times the hourly rate for 
# the hours worked above 40 hours
#else pay based on hourly pay and hours worked
#input hourly rate and hours worked and display pay

rate= float(input("enter rate:"))
hour= float(input("enter hour:"))
if hour<=40:
  print(" pay =",hour*rate)
else:
  print("pay =",(hour-40)*1.5*rate+(40*rate))

enter rate:10
enter hour:50
pay = 550.0


In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(8,1,-2):
  print(i)

8
6
4
2


In [ ]:
n=int(input("enter the no. of students:"))

for i in range(n):
  marks1 = int(input("Enter Marks1 :"))
  marks2 = int(input("Enter Marks2 : "))
  marks3 = int(input("Enter Marks3 : "))
  total = marks1 + marks2 + marks3
  average = total/3
  if average >= 75:
        print("Qualified")
  else:
        print("Not Qualified")

enter the no. of students:2
Enter Marks1 :2
Enter Marks2 : 2
Enter Marks3 : 2
Not Qualified
Enter Marks1 :2
Enter Marks2 : 2
Enter Marks3 : 2
Not Qualified


In [ ]:
noOfStudents = int(input("Enter the Number of Students : "))
counter = 1
while counter <= noOfStudents:
    
    marks1 = int(input("Enter Marks1 :"))
    marks2 = int(input("Enter Marks2 : "))
    marks3 = int(input("Enter Marks3 : "))
    total = marks1 + marks2 + marks3
    average = total/3
    if average >= 75:
        print("Student Qualified")
    else:
        print("Student Not Qualified")
    counter += 1
print("Outside While")

In [ ]:
n=int(input("enter no. :"))
for i in range(1,n+1):
  print(i*i)
i=0
while(i<n):
  i=i+1
  print(i*i)

enter no. :3
1
4
9
1
4
9


In [ ]:
while True:
    line = input('Enter the input: ')
    if line == '#':
        continue
    if line == 'done':
        break
    print(line)
print('Done!')

Enter the input: #
Enter the input: done
Done!


In [ ]:
n=int(input("enter no:"))
i=1
while(i<=5):
  n=n+1
  count=2
  isPrime=1
  while count <= n//2:
    if n%count==0:
      isPrime=0
      break
    else:
      count=count+1
  if isPrime == 1:
   print(n)
   i=i+1
  
  


enter no:3
5
7
11
13
17


In [ ]:
s='sss'
print(len(s))
print(s[len(s)-1])
for i in s:
   print(i)


3
s
s
s
s


In [ ]:
st="apple"
i=1
for j in st:
  print(j*i)
  i=i+1

a
pp
ppp
llll
eeeee


In [ ]:
st="apple"
for char in st:
  print(char,end="")

apple

In [ ]:
st="apple"
for i in range(len(st)-1,-1,-1):
 print(st[i],end="")

elppa

In [ ]:
s="MontyPython"
print(s[0:5])
print(s[6:12:2])
print(s[3:])
print(s[1:6:2])


Monty
yhn
tyPython
otP


In [ ]:
s = 'abcdefghijk'
print(s[:5:2])
print(s[3:3])


ace



In [ ]:
#Strings are immutable
greeting = 'Hello class'
print(greeting[0])
print(id(greeting))
# this is a wrong code
#greeting[2]='s'
greeting = "Good afternoon"
print(id(greeting))

H
139996153638512
139996153637936


In [ ]:
a="abracadabra"
c=0
for i in a:
  if i=='a':
   c=c+1
print(c)

5


In [ ]:
#enumerate- returns both index and characters
st='apple is a friut'
c=0
for i,char in enumerate(st):
   if char=='a':
     c=c+1
print(c)

2


In [ ]:
stmt="Shakespeare was born and raised in Stratford-upon-Avon"
count = 0
for i,char in enumerate(stmt):    
    if char=='a':
        count = count + 1
        print(i,end=' ')
        
print('\n count = ',count)

2 8 13 21 26 38 
 count =  6


In [ ]:
word = 'carrot'
if word < 'banana':
    print('Your word,' + word + ', comes before banana.')
elif word > 'banana':
    print('Your word,' + word + ', comes after banana.')
else:
    print('All right, bananas.')

Your word,carrot, comes after banana.


In [ ]:
st=input("enter a word")
if st == st[::-1]:
 print("palindrome")
else:
  print("not palindrome")

enter a wordasdf
not palindrome


In [ ]:
st='lee'
print(dir(st))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [ ]:
# String methods
# 1. upper,lower,title
word = 'banana is a fruit'
new_word = word.upper()
print(new_word)
print(new_word.lower())
print(word.title())
print(word.islower())
#titleCase: first letter of every word is capital

BANANA IS A FRUIT
banana is a fruit
Banana Is A Fruit
True


In [ ]:
word='India Is a great Country'
i=word.find('a',word.find('a')+1)
print(i)

9


In [ ]:
#split,strip,startswith
s="this book is blue in color"
l1=s.split(' ')
print(l1)
l2=s.split('b')
print(l2)

['this', 'book', 'is', 'blue', 'in', 'color']
['this ', 'ook is ', 'lue in color']


In [ ]:
l='@dsjhds@'
print(l.strip('@'))

dsjhds


In [ ]:
'''
Assume you have 5 strings as given below
find out the mean of X-DSPAM-Confidence and 
Y-DSPAM-Confidence
' X-DSPAM-Confidence:0.8475 '
' X-DSPAM-Confidence:0.765 '
' X-DSPAM-Confidence:0.7065 '
'Y-DSPAM-Confidence:0.9985 '
'Y-DSPAM-Confidence:0.6585 '
'''
Data = [' X-DSPAM-Confidence:0.8475 ',' X-DSPAM-Confidence:0.765 ',
        ' X-DSPAM-Confidence:0.7065 ','Y-DSPAM-Confidence:0.9985 ',
        'Y-DSPAM-Confidence:0.6585 ']

In [ ]:
Data = [' X-DSPAM-Confidence:0.8475 ',' X-DSPAM-Confidence:0.765 ',
        ' X-DSPAM-Confidence:0.7065 ','Y-DSPAM-Confidence:0.9985 ',
        'Y-DSPAM-Confidence:0.6585 ']
yCount=0
xCount=0
xNum=0
yNum=0
for i in Data:
  j=i.strip(' ')
  if(j.startswith('X')):
    xNum=xNum+float(j.split(":")[1])
    xCount=xCount+1  
  if(j.startswith('Y')):
    yNum=yNum+float(j.split(":")[1])
    yCount=yCount+1

print('mean of X-DSPAM-Confidence is ',(xNum/xCount))
print('mean of Y-DSPAM-Confidence is ',(yNum/yCount))

mean of X-DSPAM-Confidence is  0.773
mean of Y-DSPAM-Confidence is  0.8285


In [ ]:
str="a1b1c1"
str.replace('1','')

'abc'

In [ ]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
s=input("enter string: ")
for i in s:
  if i in punctuations:
    s=s.replace(i,'')
print(s)

enter string: !sd@ss!
sdss


In [ ]:
#list
x=[2, 'a', 4.5, False]
print(x)

[2, 'a', 4.5, False]


In [ ]:
l=[1,2,3,4,5]
print(3 in l)

True


In [ ]:
l1=list(range(10))
print(l1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
l1=list(range(5,51,5))
print(l1)
print(l1[2:7])
print(l1[2:7:2])
print(l1[7:2:-1])
print(l1[:6:-1])
print(l1[::-1])

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
[15, 20, 25, 30, 35]
[15, 25, 35]
[40, 35, 30, 25, 20]
[50, 45, 40]
[50, 45, 40, 35, 30, 25, 20, 15, 10, 5]


In [ ]:
l=['raju','isw']
s= ' '.join(l)
print("fd,"+s+' ds')


fd,raju iswds


In [ ]:
# Extract the integer part out of each element in myList
l=[34.5,23,5,34,23.56]
l1=[]
for i in l:
  l1.append(int(i))
print(l1)

[34, 23, 5, 34, 23]


In [ ]:
l=[34.5,23,5,34,23.56,0]
l1=[]
print(len(l))
for i in range(0,int(len(l)/2)):
  l1.append(l[i])
print(l1)

l2=[]
for i in l:
  l2.append(int(i/2))
print(l2)

6
[34.5, 23, 5]
[17, 11, 2, 17, 11, 0]


In [ ]:
#extend
#helps to add elements to string
#but the difference between append and extend is
#extend adds the element of the new list toward the end

In [ ]:
x = [7,6,4,5,90,75,2,1]
#add a new elements using append
y=["Hello","how","are","you"]
x.append(y)
print(x)
x = [7,6,4,5,90,75,2,1]
#add a new elements using extend
y=["Hello","how","are","you"]
x.extend(y)
print(x)


[7, 6, 4, 5, 90, 75, 2, 1, ['Hello', 'how', 'are', 'you']]
[7, 6, 4, 5, 90, 75, 2, 1, 'Hello', 'how', 'are', 'you']


In [ ]:
A = [10,20,30,40]
B = [20,30,40,50]
C=A+B
print(C) #concate
print(A*2)#repeat the elements
A.extend(B)
print(A)

[10, 20, 30, 40, 20, 30, 40, 50]
[10, 20, 30, 40, 10, 20, 30, 40]
[10, 20, 30, 40, 20, 30, 40, 50]


In [ ]:
#sort
x=[2,4,1,8,4]
x.sort()
print(x)
x.sort(reverse=True)
print(x)

[1, 2, 4, 4, 8]
[8, 4, 4, 2, 1]


In [ ]:
#ternary operator
x=5
y=6
print(x) if(x>y) else print(y)

6


In [ ]:
x=10
print('even') if(x%2==0) else print('odd')

even


In [ ]:
#list comprehension
l1=list(range(1,30,5))
l2=[i*2 for i in l1]
print(l2)
l1=list(range(1,30,5))
l2=[i*2 for i in l1]
print(l2)

[2, 12, 22, 32, 42, 52]
[2, 12, 22, 32, 42, 52]


In [ ]:
#Program to display the first three letters of the list element in upper case
wordList = ["India","Australia","USA","France"]
l1=[i[:3].upper() for i in wordList]
print(l1)

['IND', 'AUS', 'USA', 'FRA']


In [ ]:
l1=[11,12,13,14,15,16]
l2=[n*2 if n%2==0 else n*3 for n in l1]
print(l2)

[33, 24, 39, 28, 45, 32]


In [ ]:
#Write a program to multiply every even number of the list by 5
l1=[11,12,13,14,15,16]
l2=[n*5 for n in l1 if n%2==0]
print(l2)

[60, 70, 80]


In [ ]:
#find the length of the element if the element starts with 'A'
words=['Apple','Banana','Ant','Aeroplane','anger']
l1=[len(i) for i in words if i.startswith('A')]
print(l1)

[5, 3, 9]


In [ ]:
#find the length of the element if the element starts with 'A' else display the first letter in caps
words=['Apple','Banana','Ant','Aeroplane','anger']
l1=[len(i) if i[0]=='A' else i[0].upper() for i in words ]
print(l1)

[5, 'B', 3, 9, 'A']


In [ ]:
#display all elements which are divisible by 2 and 5
x = [2, 30, 15, 10]
l1=[i for i in x if i%2==0 and i%5==0]
print(l1)

[30, 10]


In [ ]:
#methods to remove elements from list
t = [1,2,3,4,'d']
t.pop(2)
print(t)
del t[1:3]
print(t)
t.remove('d')
print(t)

[1, 2, 4, 'd']
[1, 'd']
[1]


In [ ]:
#list are mutable

In [ ]:
#built in functions
import random
for i in range(10):
  x=random.random()
  print(x)

0.4273651911873343
0.7213473906940668
0.4751815887915708
0.8607974636204707
0.8417676165756682
0.5761272263411605
0.9846921647173866
0.8287404113943071
0.8698462873812515
0.5837197216476535


In [ ]:
#for i in range(10):
x=random.randint(1,5)
print(x)

2


In [ ]:
import math
signal_power=5.6
noise_power=3.1
ratio = signal_power / noise_power
decibels = 10 * math.log10(ratio)
radians = 0.7
    
height = math.sin(radians)
degrees = 45
radians = degrees / 360.0 * 2 * math.pi
math.sin(radians)
math.sqrt(2) / 2.0
x = math.cos(radians)
golden = (math.sqrt(5) + 1) / 2

In [ ]:
help(math.pi)
help(random.random)

In [ ]:
# defining void funtions
def print_lyrics(a):
    print("I'm a lumberjack, and I'm okay.")
    print('I sleep all night and I work all day.')
    print(a)
    return(5)
print(print_lyrics('blahhhh'))

I'm a lumberjack, and I'm okay.
I sleep all night and I work all day.
blahhhh
5


In [ ]:

def fibo(n):
  count=0
  a,b=0,1
  while(count<n):
    print(a)
    c=a+b
    a=b
    b=c
    count=count+1
n=int(input('enter no:'))
fibo(n)

enter no:8
0
1
1
2
3
5
8
13


In [ ]:
# funciton for fibanocci series
def gen_fib(f):
    x=0
    y=1
    print(x,"",y, end=" ")
    z=x+y
    while y < f:        
        print(z,end=" ")
        x,y=y,z
        z=x+y
        
fib=int(input())
gen_fib(fib)

6
0  1 1 2 3 5 8 

In [ ]:
stmt="ABCDEFGHIJKLM"
print(stmt[10:3:-1])

KJIHGFE


In [ ]:

def isPrime(n1,n2):
  i=n1
  while(i<=n2):
    n1=n1+1
    count=2
    isPrime=1
    while count <= n1//2:
      if n1%count==0:
        isPrime=0
        break
      else:
        count=count+1
    if isPrime == 1:
      print(n1)
    i=i+1
n1=int(input("enter no1:"))
n2=int(input("enter no2:"))
isPrime(n1,n2)

enter no1:20
enter no2:50
23
29
31
37
41
43
47


In [ ]:
l1=[5,6,4,89,34,56,23,21]
l2=[isPrime(i) for i in l1]

In [ ]:
def is_prime(number):
    count = 2
    isPrime = True #The number is assumed to be prime
    if(number > 1):
        half=number//2
        for count in range(2,half+1):
            if number % count == 0:
                isPrime = False #the number is not prime
                break
    else:
        isPrime = False
    return isPrime

In [ ]:
l1=[5,6,4,89,34,56,23,21]
l2=[i for i in l1 if(is_prime(i))]
print(l2)

[5, 89, 23]


In [ ]:
#Define a lambda function:
sum = lambda x, y : x + y
print(type(sum))
#invoke a lambda function:
sum(3,4)

<class 'function'>


7

In [ ]:
sq = lambda x:x**2
print(sq)
sq(5)

In [ ]:
l1=[5,6,4,89,34,56,23,21]
X=map(is_prime,l1)
print(list(X))

[True, False, False, True, False, False, True, False]


map(function name,iterable(like list,tuple))
the function will be applied to every ele of the list


In [ ]:
temperatures = [36.5, 37, 37.5, 38, 39]
F = map(lambda T: round(((float(9)/5)*T + 32),2), temperatures)
print(list(F))

[97.7, 98.6, 99.5, 100.4, 102.2]


In [ ]:
#find the square of every list element using map and lambda
nums = [2, 4, 6, 8, 10]
X=map((lambda i:i**2),nums)
print(list(X))

[4, 16, 36, 64, 100]


In [ ]:
#filter method
lst = [2,3,5,6,8,7,9,10]
result = filter(lambda i: i%2==0, lst)
print(list(result))

[2, 6, 8, 10]


In [ ]:
#find the length of the element if the element starts with 'A' else display the first letter in caps
words=['Apple','Banana','Ant','Aeroplane','anger']
res=map(lambda x:len(x) if x.startswith('A') else x[0].upper(),words)
print(list(res))

[5, 'B', 3, 9, 'A']


In [ ]:
R=filter(lambda i:len(i)>4,words)
print(list(R))

['Apple', 'Banana', 'Aeroplane', 'anger']


In [ ]:
#For all 3 digit number divide the numebr by 2
#res=map(lambda x:len(x) if x.startswith('A') else x[0].upper(),words)
#print(list(res))
num=[12,554,2,456,23,123]
ThreeDigitNum = list(filter(lambda x: len(str(x))==3,num))
print(ThreeDigitNum)
list(map(lambda x: round(x/2,2),ThreeDigitNum))


TypeError: ignored

In [ ]:
#functools
#reduce: it reduces list into single element
#like for finding sum,avg..
from functools import reduce
lst = [10,20,30,40,50]
reduce(lambda x, y: x+y, lst)


150

In [ ]:
reduce(lambda a,b: a if (a < b) else b, [47,11,42,42,13])

11

In [ ]:
R=reduce(lambda i,j:i*j,range(1,7))
print(R)

720


In [ ]:
a = [1,2,3,4]
b = [17,12,11,10]
c = [-1,-4,5,9]
print(list(map(lambda x,y: x+y,a,b)))
print(list(map(lambda x,y,z:x+y+z, a,b,c)))
print(list(map(lambda x,y,z:x+y-z, a,b,c)))

[18, 14, 14, 14]
[17, 10, 19, 23]
[19, 18, 9, 5]


In [ ]:
mass=[45,55,65,76]
ht=[1.65,1.70,1.55,1.80]
print(list(map(lambda x,y:x/(y**2),mass,ht)))

[16.528925619834713, 19.031141868512112, 27.055150884495315, 23.456790123456788]


In [ ]:
#dictionary
x = {"a": 1, 
     "b": 4.45, 
     2  : " A string"}
print(type(x))
print(x[2])
print(x)
print(x.values())
print(x.items())


<class 'dict'>
 A string
{'a': 1, 'b': 4.45, 2: ' A string'}
dict_values([1, 4.45, ' A string'])
dict_items([('a', 1), ('b', 4.45), (2, ' A string')])


In [ ]:
e=dict()
e={} #empty dictionary

In [ ]:
#Write a Python script to generate and print a dictionary that contains a number (between 1 and n) in the form (x, x*x)

In [ ]:
n=int(input("enter n:"))
d={}
for x in range(1,n+1):
  d[x]=x*x
print(d)

enter n:5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [ ]:
my_dict = {'data1':100,'data2':-54,'data3':247}
R=reduce(lambda i,j:i+j,list(my_dict.values()))
print(R)

293


In [ ]:
counts = { 'chuck' : 1 , 'annie' : 42, 'jan': 100}
for i in counts:
  if counts[i]>10:
    print(i,counts[i])

annie 42
jan 100


In [ ]:
get method
if key is present it will return its value
else will return the default value

In [ ]:
print(counts.get('jan',0))
print(counts.get('ann',10))

100
10


In [ ]:
players=["Sachin","Ganguly","Dravid","Kumble","Sehwag"]
score={"Sachin":98,"Ganguly":78,"Dravid":102}
for i in players:
   print(score.get(i,'NA'))
 

98
78
102
NA
NA


In [ ]:
word = 'brontosaurus'
d = dict()
for c in word:
    if c not in d:
        d[c] = 1
    else:
        d[c] = d[c] + 1
print(d)

{'b': 1, 'r': 2, 'o': 2, 'n': 1, 't': 1, 's': 2, 'a': 1, 'u': 2}


In [ ]:
d1={}
for c in word:
  d1[c]=d1.get(c,0)+1
print(d1)

{'b': 1, 'r': 2, 'o': 2, 'n': 1, 't': 1, 's': 2, 'a': 1, 'u': 2}


In [ ]:
d1={}
for c in word:
  if(c in 'aeiou'):
   d1[c]=d1.get(c,0)+1
print(d1)

{'o': 2, 'a': 1, 'u': 2}


In [ ]:
#program to replace vowel with numbers
S = "rennaissance"
list1 = []
l=list(S)
print(l)
v = {'a':'1','e':'2','i':'3','o':'4','u':'5'}
for i in range(0,len(l)):
  if(l[i] in 'aeiou'):
    l[i]=v.get(l[i],l[i])
print(l)
l1="".join(l)
print(l1)
    


['r', 'e', 'n', 'n', 'a', 'i', 's', 's', 'a', 'n', 'c', 'e']
['r', '2', 'n', 'n', '1', '3', 's', 's', '1', 'n', 'c', '2']
r2nn13ss1nc2


In [ ]:
Group of 4 families from Radiant Shine apartment plan for a picnic event during the summer vacation. During this event they plan to organise games for their family members.The game is as follows 
First person  has to say  a word  S,the other person has to give the modified word that  has only the distinct character in S. The characters should be presented in the descending order of its occurrence. If the occurrence count of two characters is same , then the order of these two characters should be the same as it is in S
Input Format :
Input is a string that denotes S 
Note : The string is case sensitive
Output Format :
The output is a string that denotes the modified string .

In [ ]:
s=input("Enter the string")
a_count=dict()
for i in s:
    a_count[i]= a_count.get(i,0) + 1
a_rev=list(sorted(a_count.items(),key=lambda kv:kv[1],reverse=True))
output_str=''
for i in range(len(a_rev)):
    output_str=output_str+a_rev[i][0]
print(output_str)

Enter the stringsanjana
ansj


In [ ]:
#tuple
#tuples are immutable
#list are mutable
#tuples are faster than list

In [ ]:
t=('a',1,34,'fg',3)
print(t[:2])

('a', 1)


In [ ]:
t = ('a', 'b', 1, 2, 'e',1,2)
print(t)
print(type(t))

('a', 'b', 1, 2, 'e', 1, 2)
<class 'tuple'>


In [ ]:
#file handling
#read write append create


"r" - Read - Default value. Opens a file for reading, error if the file does not exist
"a" - Append - Opens a file for appending, creates the file if it does not exist
"w" - Write - Opens a file for writing, creates the file if it does not exist
"x" - Create - Creates the specified file, returns an error if the file exists

In [ ]:
#file creation
with open("SampleFile.txt","w") as f_hand:
    f_hand.write("This is the first line\n")
f_hand.close()

In [ ]:
fhand=open('SampleFile.txt','r')
print(fhand.read())
fhand.close()

This is the first line



In [ ]:
#1.What will happen if you write another line?
with open("SampleFile.txt","a") as f_hand:
    f_hand.write("python is a \n")
f_hand.close()

In [ ]:
fhand=open('SampleFile.txt','r')
print(fhand.read(20))
fhand.close()

Tne
Tne
python is a 


In [ ]:
file=open("SampleFile.txt","r")
for line in file:
  if line.find("python")>=0:
    print(line)


python is a 



In [ ]:
file=open("SampleFile.txt","r")
for line in file:
  if line.startswith("python"):
    print(line)

python is a 



In [ ]:
#regular experssion
import re
#search findall
d={}
file= open("SampleFile.txt")
for line in file:
  line=line.rstrip()
  print(re.findall('[aeiou]',line))
  for i in re.findall('[aeiouAEIOU]',line):
    d[i]=d.get(i,0)+1
print(d)
    

['e']
['e']
['o', 'i', 'a']
{'e': 2, 'o': 1, 'i': 1, 'a': 1}


In [ ]:
txt = "Catsan dDogsareanimals"
x = re.search("^Cats.*ls$", txt)
print(x)

<_sre.SRE_Match object; span=(0, 22), match='Catsan dDogsareanimals'>


In [ ]:
^        Matches the beginning of a line
$        Matches the end of the line
.        Matches any character
\s       Matches whitespace
\S       Matches any non-whitespace character
*        Causes the resulting RE to match 0 or more repetitions of the preceding RE, as many repetitions as are possible. 
         e.g: ab* will match ‘a’, ‘ab’, or ‘a’ followed by any number of ‘b’s
*?       Repeats a character zero or more times (non-greedy)
+        Causes the resulting RE to match 1 or more repetitions of the preceding RE. 
         e.g:ab+ will match ‘a’ followed by any non-zero number of ‘b’s; it will not match just ‘a’.
?        Causes the resulting RE to match 0 or 1 repetitions of the preceding RE. 
         e.g:ab? will match either ‘a’ or ‘ab’.
+?       Repeats a character one or more times (non-greedy)
[aeiou]  Matches a single character in the listed set
[^XYZ]   Matches a single character not in the listed set
[a-z0-9] The set of characters can include a range

In [ ]:
txt = "Catsan dDogsareanimals"
x = re.search("^Cats.*\s+.*ls$", txt)
print(x)

<_sre.SRE_Match object; span=(0, 22), match='Catsan dDogsareanimals'>


In [ ]:
#split
txt="catsn d Do gs are animals"
x=re.split("\s", txt,3)
print(x)

['catsn', 'd', 'Do', 'gs are animals']


In [ ]:
#greedy and non greedy
s='<html><head><title>'
print(re.match('<.*>',s).span())
print(re.findall('<.*>',s))

print(re.match('<.*?>',s).span())
print(re.findall('<(.*?)>',s)) #()=only will extract inside ()

(0, 19)
['<html><head><title>']
(0, 6)
['html', 'head', 'title']


In [ ]:
import re
s = 'raja ram mohan roy '
print(re.findall(' ', s))

[' ', ' ', ' ', ' ']


In [ ]:
    print(re.findall('(.+?)\s', s))

['raja', 'ram', 'mohan', 'roy']


In [ ]:
s='G-34GRADING system offers 3432 weightage to 342.32 units'
re.findall('[0-9]',s) #all no.

['3', '4', '3', '4', '3', '2', '3', '4', '2', '3', '2']

In [ ]:
print(re.findall("[0-9]+[.]*[0-9]+", s)) #all no.

['34', '3432', '342.32']


In [ ]:
# \d indicats digits
print(re.findall("\d+[.]*[\d]*", line))

[]


In [ ]:
print(re.findall('[^0-9.]+',line)) #everything other than decimal point

['python is a']


In [ ]:
fhand=open('CHAT.txt','r')
print(fhand.read(30))
fhand.close()

September 11, 2020	    1:49:30


In [ ]:
file=open("CHAT.txt","r")
dict={}
for line in file:
    line=line.rstrip()
    if(re.search('from',line)):
        l1=line.split('from')
        l2=l1[1].split('to')
        dict[l2[0]]=dict.get(l2[0],0)+1
print(dict)

{' Priya Prabhu ': 3, ' Amogh Simha ': 1, ' Jigyasa  Handa ': 13, ' Rachana GVD ': 19, ' Anay Kha': 13, ' Shashwat Singh ': 12, ' Manoj R Astikar ': 6, ' Simran Sabharwal ': 28, ' Anurag Agrawal ': 11, ' Aishani ': 12, ' Archana ': 19, ' Arya Saumitra ': 1, ' Nishtha ': 6, ' Deepthi Bhat ': 15, ' Priyesh Saraswat ': 7, ' Adithya Narayan ': 5, ' Faraz Umar ': 2, ' El': 3, ' Nagashri H J ': 4, ' Sri Lakshmi J ': 2, ' Rishu Verma ': 1, ' Rohith Janardhan ': 1, ' Sanjitha M ': 2, ' srilekha ': 8, ' Ayesha ': 7, ' Richa Ranjan ': 1, ' Mona Teja ': 1}


In [ ]:
s='He said abc@yahoo.com used kar@gmail.com'
print(re.findall('@(\S*).com',s))
print(re.findall('@([A-Za-z0-9]+).',s))
print(y)
#x = re.search("^Cats.*\s+.*ls$", txt)

['yahoo', 'gmail']
['yahoo', 'gmail']
['yahoo.com', 'gmail.co']


NumPy
was created in 2005 by Travis Oliphant.
stands for Numerical Python.
provide an array object that is up to 50x faster that traditional Python lists.
stored at one continuous place in memory unlike lists
written mostly in C and C++
https://github.com/numpy/numpy

In [ ]:
import numpy as np
x=[1,3,6,9]
print(x)


[1, 3, 6, 9]


In [ ]:
list(map(lambda i: i*10,x))

[10, 30, 60, 90]

In [ ]:
nparry=np.array(x)
print(nparry) #no comma

[1 3 6 9]


In [ ]:
print(nparry/2)

[0.5 1.5 3.  4.5]


In [ ]:
#filtering in numpy
print((nparry % 3)==0)
print(nparry[nparry %3 == 0])

[False  True  True  True]
[3 6 9]


In [ ]:
print(nparry[nparry < 5])

[1 3]


In [ ]:
dir(nparry)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [ ]:
nparry.max()

9

In [ ]:
nparry.argmax() #gives the position of the max ele

3

In [ ]:
nparry.mean()

4.75

In [ ]:
np.average(nparry)

4.75

In [ ]:
nparray=np.array([-4000,3.8,3,5])
print(type(nparray))
nparray.shape

<class 'numpy.ndarray'>


(4,)

In [ ]:
np1=np.array([[1,2,3],[4,5,6]])
print(np1)
np1.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
npX3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7,8,9], [10, 11, 12]]])

In [ ]:
npX3d.shape

(2, 2, 3)

In [ ]:
print(npX3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
npX3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
npX3d[1,0][1]

8

In [ ]:
npX3d[1,0,1]

8

In [ ]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((2,3) )

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
print(npX3d)
print(npX3d[:1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[1 2 3]
  [4 5 6]]]


In [ ]:
#another method to create a numpy
x=np.arange(1,20,2)
print(x)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
x.reshape((2,5))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [ ]:
x.flatten()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
nparr1 = np.array([[1, 2, 3], [4, 5, 6]])
nparr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(nparr1+nparr2) #it sums up

[[ 8 10 12]
 [14 16 18]]


In [ ]:
#contact
np.concatenate([nparr1,nparr2],axis=0)#axis=0 row wise concate

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([nparr1,nparr2],axis=1)#axis=1 col wise concate

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
newarr=np.vstack((nparr1,nparr2))
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
newarr=np.hstack((nparr1,nparr2))
print(newarr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
narr = np.arange(9)
print(narr)
print(np.array_split(narr,2))

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8])]


In [ ]:
outcome=np.random.random(size=10)
print(outcome)

[0.96662808 0.05092331 0.83149427 0.72603123 0.32897203 0.89293887
 0.04251489 0.79381446 0.8778723  0.98325105]


In [ ]:
outcome=np.random.randint(1,7,size=10)
print(outcome)

[3 4 6 4 1 4 2 2 1 2]


In [ ]:
x = [10, 11, 12, 34]
r=np.random.shuffle(x)
print(x)

[34, 12, 11, 10]


In [ ]:
np.sort(outcome)

array([1, 1, 2, 2, 2, 3, 4, 4, 4, 6])

In [ ]:
-(np.sort(-outcome)) 

array([6, 4, 4, 4, 3, 2, 2, 2, 1, 1])

In [ ]:
#pandas
#dataframe is the advatage of pandas
#from series to dataframe

In [ ]:
import pandas as pd

In [ ]:
#create a series
s=pd.Series([4,5,4.5,'2'])
print(s)

0      4
1      5
2    4.5
3      2
dtype: object


In [ ]:
s=pd.Series([4,5,4.5,8],index=["a","b","c","d"]) #u can assign index
print(s)

a    4.0
b    5.0
c    4.5
d    8.0
dtype: float64


In [ ]:
s[s<5]

a    4.0
c    4.5
dtype: float64

In [ ]:
dictionary = {"First":["Hi","Hello"],"Second": 5.4,
              "Third":-9.4,"Fourth":12}
series = pd.Series(dictionary)
print(series) #key is the index

First     [Hi, Hello]
Second            5.4
Third            -9.4
Fourth             12
dtype: object


In [ ]:
a=pd.Series([10,20,30])
b=pd.Series([1,2,3])
print(a+b)

0    11
1    22
2    33
dtype: int64


In [ ]:
data = {"date" : [ "December,2014", "December, 2013",
                  "December, 2012","December,2011"],
        "global_temp": [0.87,0.74,0.65,0.63]
       }
df = pd.DataFrame(data)
print(df) #it doesnt create df if it has uneven values
#df has heading ex:date global_temp

             date  global_temp
0   December,2014         0.87
1  December, 2013         0.74
2  December, 2012         0.65
3   December,2011         0.63


In [ ]:
dataframe = pd.DataFrame(np.random.randn(20,5),columns
                         = ['A','B','C','D','E'])
print(dataframe)

           A         B         C         D         E
0   0.491696  1.639212 -1.304441 -1.359193  1.455568
1  -1.560374 -1.706681 -0.175872 -1.159303  0.227028
2  -0.887140 -0.164894  1.240438  0.429743 -1.069185
3   1.950536 -0.876273 -0.094301  0.194155  1.538443
4   0.848150  0.298579 -0.465975  2.147101 -1.749231
5   0.068465  0.296886 -0.212366  0.086114 -1.873571
6   1.035242  0.624416  0.428326  0.439406 -1.596122
7   2.274976 -0.379161  0.388391 -2.849557  0.935922
8  -0.939794  0.482816  0.411376 -1.011155  0.970016
9  -0.597164  0.222933  0.101982  0.884353  0.492091
10 -0.102981  1.106836  1.134287  0.202582 -0.924154
11 -0.094183  1.022851 -0.611165  1.166761 -0.653144
12  0.869822 -0.500866 -1.124080  0.120168  0.271898
13  0.150056  0.043467  0.033079  1.526046 -1.676818
14  0.064589  0.550522  0.885465 -0.991275  0.535943
15  0.355089  0.221525 -0.930877 -0.035358 -1.275549
16  0.683921 -1.452178  0.973317 -0.226124  0.330249
17 -0.064860 -1.420648  0.280996 -0.086148 -0.

In [ ]:
dataframe.head()

A         B         C         D         E
0  0.491696  1.639212 -1.304441 -1.359193  1.455568
1 -1.560374 -1.706681 -0.175872 -1.159303  0.227028
2 -0.887140 -0.164894  1.240438  0.429743 -1.069185
3  1.950536 -0.876273 -0.094301  0.194155  1.538443
4  0.848150  0.298579 -0.465975  2.147101 -1.749231

In [ ]:
dataframe.tail(n=3)

A         B         C         D         E
17 -0.064860 -1.420648  0.280996 -0.086148 -0.665627
18 -1.427598  0.752225  1.294852 -0.885677 -0.538869
19  0.342315 -0.184245  3.211465  0.152545 -0.562954

In [ ]:
dataframe.describe()

A          B          C          D          E
count  20.000000  20.000000  20.000000  20.000000  20.000000
mean    0.173038   0.028866   0.273245  -0.062741  -0.291403
std     0.985057   0.887782   1.029942   1.116051   1.085759
min    -1.560374  -1.706681  -1.304441  -2.849557  -1.873571
25%    -0.226526  -0.409587  -0.275768  -0.912077  -1.120776
50%     0.109261   0.222229   0.191489   0.103141  -0.550911
75%     0.724979   0.568995   0.907428   0.432159   0.503054
max     2.274976   1.639212   3.211465   2.147101   1.538443

In [ ]:
dataframe.sort_values(by=['A','C'])

A         B         C         D         E
1  -1.560374 -1.706681 -0.175872 -1.159303  0.227028
18 -1.427598  0.752225  1.294852 -0.885677 -0.538869
8  -0.939794  0.482816  0.411376 -1.011155  0.970016
2  -0.887140 -0.164894  1.240438  0.429743 -1.069185
9  -0.597164  0.222933  0.101982  0.884353  0.492091
10 -0.102981  1.106836  1.134287  0.202582 -0.924154
11 -0.094183  1.022851 -0.611165  1.166761 -0.653144
17 -0.064860 -1.420648  0.280996 -0.086148 -0.665627
14  0.064589  0.550522  0.885465 -0.991275  0.535943
5   0.068465  0.296886 -0.212366  0.086114 -1.873571
13  0.150056  0.043467  0.033079  1.526046 -1.676818
19  0.342315 -0.184245  3.211465  0.152545 -0.562954
15  0.355089  0.221525 -0.930877 -0.035358 -1.275549
0   0.491696  1.639212 -1.304441 -1.359193  1.455568
16  0.683921 -1.452178  0.973317 -0.226124  0.330249
4   0.848150  0.298579 -0.465975  2.147101 -1.749231
12  0.869822 -0.500866 -1.124080  0.120168  0.271898
6   1.035242  0.624416  0.428326  0.439406 -1.596122
3   1.950536 -0.876273 -0.094301  0.194155  1.538443
7   2.274976 -0.379161  0.388391 -2.849557  0.935922

In [ ]:
dataframe.A
dataframe[['A','B']]

A         B
0   0.491696  1.639212
1  -1.560374 -1.706681
2  -0.887140 -0.164894
3   1.950536 -0.876273
4   0.848150  0.298579
5   0.068465  0.296886
6   1.035242  0.624416
7   2.274976 -0.379161
8  -0.939794  0.482816
9  -0.597164  0.222933
10 -0.102981  1.106836
11 -0.094183  1.022851
12  0.869822 -0.500866
13  0.150056  0.043467
14  0.064589  0.550522
15  0.355089  0.221525
16  0.683921 -1.452178
17 -0.064860 -1.420648
18 -1.427598  0.752225
19  0.342315 -0.184245

In [ ]:
dataframe[2:5]['A']

2   -0.887140
3    1.950536
4    0.848150
Name: A, dtype: float64

In [ ]:
dataframe[2:5][['A','B','C']]

A         B         C
2 -0.887140 -0.164894  1.240438
3  1.950536 -0.876273 -0.094301
4  0.848150  0.298579 -0.465975

In [ ]:
dataframe.iloc[[2,3,8,14],[0,1]]

A         B
2  -0.887140 -0.164894
3   1.950536 -0.876273
8  -0.939794  0.482816
14  0.064589  0.550522

In [ ]:
dataframe[dataframe.A>0.1][['A','B','C']]

A         B         C
0   0.491696  1.639212 -1.304441
3   1.950536 -0.876273 -0.094301
4   0.848150  0.298579 -0.465975
6   1.035242  0.624416  0.428326
7   2.274976 -0.379161  0.388391
12  0.869822 -0.500866 -1.124080
13  0.150056  0.043467  0.033079
15  0.355089  0.221525 -0.930877
16  0.683921 -1.452178  0.973317
19  0.342315 -0.184245  3.211465

In [ ]:
dataframe[(dataframe.A>0.1) & (dataframe.A<0.2 )][['A','B','C']]

A         B         C
13  0.150056  0.043467  0.033079

In [ ]:
dataframe[(dataframe.A>0.1) & (dataframe.B<0.2 )][['A','B','C']]

A         B         C
3   1.950536 -0.876273 -0.094301
7   2.274976 -0.379161  0.388391
12  0.869822 -0.500866 -1.124080
13  0.150056  0.043467  0.033079
16  0.683921 -1.452178  0.973317
19  0.342315 -0.184245  3.211465

In [ ]:
dataframe=dataframe.drop('C',axis=1)
print(dataframe.head())

          A         B         D         E
0  0.491696  1.639212 -1.359193  1.455568
1 -1.560374 -1.706681 -1.159303  0.227028
2 -0.887140 -0.164894  0.429743 -1.069185
3  1.950536 -0.876273  0.194155  1.538443
4  0.848150  0.298579  2.147101 -1.749231


In [ ]:
dataframe=dataframe.rename(columns={'A':'ID'})
print(dataframe.head())

         ID         B         D         E
0  0.491696  1.639212 -1.359193  1.455568
1 -1.560374 -1.706681 -1.159303  0.227028
2 -0.887140 -0.164894  0.429743 -1.069185
3  1.950536 -0.876273  0.194155  1.538443
4  0.848150  0.298579  2.147101 -1.749231


In [ ]:
df = pd.DataFrame({'class': ['a', 'a', 'b', 'b'],
                   'class_Name': ['Marker', 'Marker', 
                                  'Projector', 'Projector'],
                         'quantity':[12, 10, 3, 6],
                         'price':[120, 100, 30, 60]})
df

class class_Name  quantity  price
0     a     Marker        12    120
1     a     Marker        10    100
2     b  Projector         3     30
3     b  Projector         6     60

In [ ]:
grouped = df.groupby('class')
grouped.mean()

quantity  price
class                 
a          11.0  110.0
b           4.5   45.0

In [ ]:
df[['quantity','class']].groupby('class').mean()

quantity
class          
a          11.0
b           4.5

In [ ]:
df.groupby('class').agg({'quantity':np.sum,'price':np.mean})

quantity  price
class                 
a            22    110
b             9     45

In [ ]:
df.groupby('class').agg(["mean","sum","std"])

quantity               price                
          mean sum       std  mean  sum        std
class                                             
a         11.0  22  1.414214   110  220  14.142136
b          4.5   9  2.121320    45   90  21.213203

In [ ]:
df.groupby('class').agg({'quantity':"max",'price':[np.mean,np.sum]})

quantity price     
           max  mean  sum
class                    
a           12   110  220
b            6    45   90

In [ ]:
dataframe.apply(np.mean,axis=1)

0     0.556821
1    -1.049833
2    -0.422869
3     0.701715
4     0.386150
5    -0.355527
6     0.125736
7    -0.004455
8    -0.124529
9     0.250553
10    0.070571
11    0.360571
12    0.190255
13    0.010688
14    0.039945
15   -0.183573
16   -0.166033
17   -0.559321
18   -0.524980
19   -0.063085
dtype: float64

In [ ]:
dataframe.apply(lambda x:x*2,axis=1)

ID         B         D         E
0   0.983392  3.278424 -2.718386  2.911135
1  -3.120748 -3.413363 -2.318606  0.454055
2  -1.774280 -0.329788  0.859487 -2.138370
3   3.901073 -1.752545  0.388310  3.076885
4   1.696300  0.597158  4.294202 -3.498463
5   0.136929  0.593772  0.172228 -3.747141
6   2.070484  1.248833  0.878812 -3.192244
7   4.549952 -0.758321 -5.699114  1.871844
8  -1.879589  0.965631 -2.022310  1.940032
9  -1.194327  0.445866  1.768707  0.984181
10 -0.205961  2.213672  0.405163 -1.848308
11 -0.188366  2.045703  2.333522 -1.306288
12  1.739645 -1.001733  0.240336  0.543796
13  0.300113  0.086935  3.052092 -3.353636
14  0.129179  1.101043 -1.982550  1.071886
15  0.710178  0.443049 -0.070717 -2.551098
16  1.367843 -2.904355 -0.452247  0.660497
17 -0.129719 -2.841296 -0.172297 -1.331253
18 -2.855196  1.504450 -1.771355 -1.077737
19  0.684630 -0.368490  0.305089 -1.125909

In [ ]:
dataframe.head().apply(lambda x:x*2,axis=0)

ID         B         D         E
0  0.983392  3.278424 -2.718386  2.911135
1 -3.120748 -3.413363 -2.318606  0.454055
2 -1.774280 -0.329788  0.859487 -2.138370
3  3.901073 -1.752545  0.388310  3.076885
4  1.696300  0.597158  4.294202 -3.498463

In [ ]:
#inner join
#outer join....

JOINS
----------------
Emp                        Dept
-------------------      -----------
empid  deptid            deptid deptname
100     A10              A10    "Manuf"
200     A10              A20    "Prod"
300     A20              A40    "IT"
400     A30
List the employee ids and the correspondiing names of department
inner
empid   deptid   deptname
100      A10     "Manuf"
200      A10     "Manuf"
300      A20     "Prod"
left outer
100      A10     "Manuf"
200      A10     "Manuf"
300      A20     "Prod"
400      A30      NaN
right outer
100      A10     "Manuf"
200      A10     "Manuf"
300      A20     "Prod"
NaN      A40     "IT"
full outer
100      A10     "Manuf"
200      A10     "Manuf"
300      A20     "Prod"
400      A30      NaN
NaN      A40     "IT"

In [ ]:
df1  = pd.DataFrame({'key1': ['a', 'b','e','f'], 'val1': [1, 2,9,10]})
df2 = pd.DataFrame({'key2': ['a', 'b','c','d'], 'val2': [4, 5,6,7]})

In [ ]:
#merge method for join
pd.merge(df1,df2,left_on="key1",right_on="key2",how="inner")

key1  val1 key2  val2
0    a     1    a     4
1    b     2    b     5

In [ ]:
#left outer join
pd.merge(df1,df2,left_on="key1",right_on="key2",how="left")

key1  val1 key2  val2
0    a     1    a   4.0
1    b     2    b   5.0
2    e     9  NaN   NaN
3    f    10  NaN   NaN

In [ ]:
#right outer join
pd.merge(df1,df2,left_on="key1",right_on="key2",how="right")

key1  val1 key2  val2
0    a   1.0    a     4
1    b   2.0    b     5
2  NaN   NaN    c     6
3  NaN   NaN    d     7

In [ ]:
#full outer join
pd.merge(df1,df2,left_on="key1",right_on="key2",how="outer")

key1  val1 key2  val2
0    a   1.0    a   4.0
1    b   2.0    b   5.0
2    e   9.0  NaN   NaN
3    f  10.0  NaN   NaN
4  NaN   NaN    c   6.0
5  NaN   NaN    d   7.0

In [ ]:
#concate
pd.concat([df1,df2],axis=0)

key1  val1 key2  val2
0    a   1.0  NaN   NaN
1    b   2.0  NaN   NaN
2    e   9.0  NaN   NaN
3    f  10.0  NaN   NaN
0  NaN   NaN    a   4.0
1  NaN   NaN    b   5.0
2  NaN   NaN    c   6.0
3  NaN   NaN    d   7.0

In [ ]:
#pivot: to summerise data
Country   IN   SL
Year             
1960      83  143
1970     114  183
1990     375  472


In [ ]:
#pivote syntax
#print(long_data.pivot('country','year','gdppc'))

In [241]:
df=pd.read_csv("/ScoreReport.csv")
print(df.head(n=1))

   Sl.No Assessment Date  Person ID  Verbal  ...  CDP  Coding1 Coding2 RP Score
0      1      2020-05-31    46329.0       8  ...   60    100.0   100.0     73.0

[1 rows x 11 columns]


In [243]:
df[(df.Thinking>df.Verbal)][['Person ID','Verbal','Thinking']]

Person ID  Verbal  Thinking
8      46349.0       7         8
18     46351.0       4         5
20     46330.0       4         5
52     46360.0       1         2
56     46307.0       6         7
100    44602.0       3         5
122    46710.0       3         4
133    46727.0       4         6
135    46730.0       3         6
145    46740.0       4         5
146    46741.0       6         7
151    46746.0       4         5
154    46749.0       3         4
176    46999.0       3         4
185    47012.0       3         4
200    47027.0       3         4
271    47141.0       4         6
295    47180.0       5         6
310    47206.0       5         6
393    47548.0       3         5
421    47591.0       5         6
433    47635.0       5         8
454    47697.0       7         8
462    47642.0       3         4
466    47654.0       4         6
522    47678.0       5         6
536    47809.0       2         6
538    47811.0       4         5
550    47797.0       5         6
558    47834.0       5         7
565    47842.0       5         6
567    47844.0       3         4
601    47951.0       3         4
619    48014.0       7         8
640    48035.0       8        10
661    48124.0       3         4
673    48355.0       2         3
680    48363.0       3         4
687    48375.0       5         9
694    48385.0       4         5
702    48397.0       3         5
718    48419.0       4         5
733    48436.0       4         5
734    48437.0       3         5
736    48439.0       2         5
747    47392.0       3         7
749    48343.0       5         6
752    48369.0       3         4
753    48399.0       6         7
755    48428.0       3         5

In [244]:
df.iloc[[2,3,8,14],[0,1]].to_csv("output.csv")